import "./globals.css";

export const metadata = {
    title: "full-stack todo app",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                { children }
            </body>
        </html>
    )
    }